# Profil PROD - Base de données Aiven MySQL
# Le mot de passe est injecté via la variable d'environnement DB_PASS
spring.datasource.url=jdbc:mysql://mysql-277ac480-tpspring.g.aivencloud.com:15000/defaultdb?sslMode=REQUIRED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASS}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
